"""
app/engineering_exporter/exporter.py — REQ-W27-002

Engineering content generators for the weekly engineering package.

Contract:
  All generators accept (week: str, session: Session) and return str or dict.
  Generators never write to the database — they query and return content.
  The weekly router (api/weekly.py) owns all database writes.

Versioning constants (Architecture Decision B/C):
  SCHEMA_VERSION        — increments on breaking export schema change
  PACKAGE_VERSION_PREFIX — sprint prefix; router appends patch suffix
  COMPATIBLE_RUNTIME    — minimum Signal Bot version for this export schema

Pending:
  generate_timeline() is a safe placeholder pending Source Review #5 (reflex.py).
  Once reflex.py is reviewed, cross-system timeline assembly will be implemented.
"""

from datetime import datetime, timezone
from typing import Optional
import json

from sqlmodel import Session, select, func

from app.database.models import (
    Signal,
    EventLog,
    MissedOpportunity,
    EngineeringObservation,
    EngineeringReview,
    EngineeringEvidence,
)

# ─────────────────────────────────────────────────────────────
# Version constants (Architecture Decision B/C)
# ─────────────────────────────────────────────────────────────

SCHEMA_VERSION        = "engineering-export-v1"
PACKAGE_VERSION_PREFIX = "W27"
COMPATIBLE_RUNTIME    = "Signal Bot v7.9+"


# ─────────────────────────────────────────────────────────────
# Internal helpers
# ─────────────────────────────────────────────────────────────

def _doc_header(week: str, title: str, generator_version: str = "Brain Ops") -> str:
    """Standard engineering document header with version metadata."""
    now = datetime.now(timezone.utc).isoformat()
    return (
        f"---\n"
        f"Engineering Package Version : {PACKAGE_VERSION_PREFIX}.0\n"
        f"Schema Version               : {SCHEMA_VERSION}\n"
        f"Generator                    : {generator_version}\n"
        f"Generated At                 : {now}\n"
        f"Compatible Runtime           : {COMPATIBLE_RUNTIME}\n"
        f"Week                         : {week}\n"
        f"---\n\n"
        f"# {title}\n\n"
    )


def _safe_iso(dt: Optional[datetime]) -> str:
    if dt is None:
        return "—"
    return dt.isoformat()


# ─────────────────────────────────────────────────────────────
# generate_engineering_index
# ─────────────────────────────────────────────────────────────

def generate_engineering_index(week: str, session: Session) -> str:
    """
    Landing page for the weekly engineering package.
    Lists all available documents with internal links.
    """
    signals = session.exec(select(Signal).where(Signal.week == week)).all()
    eos = session.exec(
        select(EngineeringObservation).where(EngineeringObservation.sprint_opened == week)
    ).all()
    ers = session.exec(
        select(EngineeringReview).where(EngineeringReview.sprint_opened == week)
    ).all()
    events = session.exec(select(EventLog).where(EventLog.week == week)).all()

    out = _doc_header(week, f"Engineering Index — {week}")
    out += "This is the primary entry point for the weekly engineering package.\n\n"
    out += "---\n\n"
    out += "## Document Index\n\n"
    out += f"| Document | Content |\n"
    out += f"|---|---|\n"
    out += f"| [[Weekly-Summary]] | Trading intelligence summary |\n"
    out += f"| [[Runtime-Evidence]] | Chronological runtime evidence |\n"
    out += f"| [[Timeline]] | Cross-system engineering timeline |\n"
    out += f"| [[Signal-Lifecycle]] | Per-signal lifecycle export |\n"
    out += f"| [[EO-Register]] | Engineering Observations |\n"
    out += f"| [[ER-Register]] | Engineering Reviews |\n"
    out += f"| [[Engineering-Observations]] | Auto-generated behavioural observations |\n"
    out += f"| [[Runtime-Statistics]] | Aggregated runtime statistics |\n"
    out += f"| [[Engineering-Summary]] | Executive summary and findings |\n\n"
    out += "---\n\n"
    out += "## Week at a Glance\n\n"
    out += f"| Metric | Count |\n"
    out += f"|---|---|\n"
    out += f"| Signals | {len(signals)} |\n"
    out += f"| Events logged | {len(events)} |\n"
    out += f"| Engineering Observations | {len(eos)} |\n"
    out += f"| Engineering Reviews | {len(ers)} |\n\n"

    if signals:
        wins = sum(1 for s in signals if s.result == "WIN")
        losses = sum(1 for s in signals if s.result == "LOSS")
        out += f"| Wins | {wins} |\n"
        out += f"| Losses | {losses} |\n\n"

    out += "---\n\n"
    out += "## Navigation\n\n"
    out += f"← Previous week: [[{week}-prev]]  \n"
    out += f"→ Next week: [[{week}-next]]  \n\n"
    out += f"*Generated by Brain Ops — {week}*\n"
    return out


# ─────────────────────────────────────────────────────────────
# generate_timeline (placeholder)
# ─────────────────────────────────────────────────────────────

def generate_timeline(week: str, session: Session) -> str:
    """
    Cross-system engineering timeline.

    PENDING: Source Review #5 (app/api/reflex.py) is required before
    implementing cross-system timeline assembly. The Reflex observation
    persistence model in Brain Ops must be confirmed before Reflex events
    can be joined with Signal Bot events by timestamp.

    Signal Bot events (from EventLog) are included as a partial timeline.
    Reflex observation correlation is deferred.
    """
    events = session.exec(
        select(EventLog)
        .where(EventLog.week == week)
        .order_by(EventLog.event_ts)
    ).all()

    out = _doc_header(week, f"Engineering Timeline — {week}")
    out += "> **Note:** Cross-system Reflex correlation is pending Source Review #5 (reflex.py).\n"
    out += "> This timeline currently shows Signal Bot events only.\n\n"
    out += "---\n\n"
    out += "## Signal Bot Event Timeline\n\n"

    if not events:
        out += "*No events recorded for this week.*\n"
        return out

    out += "| Timestamp | Source | Event Type | Signal | Detail |\n"
    out += "|---|---|---|---|---|\n"
    for ev in events:
        signal_ref = f"[[Signal-{ev.signal_id}]]" if ev.signal_id else "—"
        detail = ev.reason or ev.state_to or ev.result or "—"
        out += (
            f"| {_safe_iso(ev.event_ts)[:19]} "
            f"| {ev.source or '—'} "
            f"| {ev.event_type} "
            f"| {signal_ref} "
            f"| {detail[:60]} |\n"
        )

    out += f"\n*{len(events)} events. Reflex correlation: pending.*\n"
    return out


# ─────────────────────────────────────────────────────────────
# generate_event_bundle
# ─────────────────────────────────────────────────────────────

def generate_event_bundle(week: str, session: Session) -> str:
    """
    Machine-readable engineering event stream as JSON.
    Every event from EventLog for the week, with version metadata.
    """
    events = session.exec(
        select(EventLog)
        .where(EventLog.week == week)
        .order_by(EventLog.event_ts)
    ).all()

    bundle = {
        "schema_version":  SCHEMA_VERSION,
        "package_version": f"{PACKAGE_VERSION_PREFIX}.0",
        "generated_at":    datetime.now(timezone.utc).isoformat(),
        "generator":       "Brain Ops",
        "runtime_version": COMPATIBLE_RUNTIME,
        "week":            week,
        "event_count":     len(events),
        "events": [
            {
                "id":             ev.id,
                "timestamp":      _safe_iso(ev.event_ts),
                "source":         ev.source,
                "event_type":     ev.event_type,
                "signal_id":      ev.signal_id,
                "direction":      ev.direction,
                "result":         ev.result,
                "state_from":     ev.state_from,
                "state_to":       ev.state_to,
                "reason":         ev.reason,
                "event_metadata": ev.event_metadata,
            }
            for ev in events
        ],
    }
    return json.dumps(bundle, indent=2, default=str)


# ─────────────────────────────────────────────────────────────
# generate_runtime_statistics
# ─────────────────────────────────────────────────────────────

def generate_runtime_statistics(week: str, session: Session) -> str:
    """
    Aggregated runtime statistics as JSON.
    Covers signals, events, missed opportunities, and lifecycle data.
    WAIT/FILTER_FAIL counts: pending W27 Runtime Validation (REQ-W27-001 data).
    """
    signals = session.exec(select(Signal).where(Signal.week == week)).all()
    events  = session.exec(select(EventLog).where(EventLog.week == week)).all()
    missed  = session.exec(select(MissedOpportunity).where(MissedOpportunity.week == week)).all()

    # Signal stats
    wins   = sum(1 for s in signals if s.result == "WIN")
    losses = sum(1 for s in signals if s.result == "LOSS")
    open_  = sum(1 for s in signals if s.result == "OPEN")
    wr     = round(wins / len(signals) * 100, 1) if signals else 0.0

    # PnL
    net_pnl = sum(s.net_pnl_usd or 0 for s in signals)

    # Event breakdown
    event_type_counts: dict = {}
    for ev in events:
        event_type_counts[ev.event_type] = event_type_counts.get(ev.event_type, 0) + 1

    # Rejection reasons
    rejection_reasons: dict = {}
    for mo in missed:
        reason = mo.rejection_reason or "unknown"
        rejection_reasons[reason] = rejection_reasons.get(reason, 0) + 1

    # Duration (signals with entry and exit)
    durations = []
    for s in signals:
        if s.signal_ts and s.exit_ts:
            delta = (s.exit_ts - s.signal_ts).total_seconds() / 3600
            durations.append(delta)
    avg_duration_h = round(sum(durations) / len(durations), 1) if durations else None

    stats = {
        "schema_version":  SCHEMA_VERSION,
        "package_version": f"{PACKAGE_VERSION_PREFIX}.0",
        "generated_at":    datetime.now(timezone.utc).isoformat(),
        "generator":       "Brain Ops",
        "runtime_version": COMPATIBLE_RUNTIME,
        "week":            week,
        "signals": {
            "total":        len(signals),
            "wins":         wins,
            "losses":       losses,
            "open":         open_,
            "win_rate_pct": wr,
            "net_pnl_usd":  round(net_pnl, 2),
            "avg_duration_hours": avg_duration_h,
        },
        "events": {
            "total":       len(events),
            "by_type":     event_type_counts,
        },
        "missed_opportunities": {
            "total":            len(missed),
            "rejection_reasons": rejection_reasons,
        },
        "filter_decisions": {
            "note": (
                "WAIT and FILTER_FAIL counts pending W27 Runtime Validation. "
                "REQ-W27-001 structured logs available in Signal Bot Railway logs."
            ),
        },
    }
    return json.dumps(stats, indent=2, default=str)


# ─────────────────────────────────────────────────────────────
# generate_eo_register
# ─────────────────────────────────────────────────────────────

def generate_eo_register(week: str, session: Session) -> str:
    """
    Export all Engineering Observations from Brain Ops database.
    Includes full lifecycle state and evidence counts.
    """
    # All EOs — not week-filtered, as EOs span multiple sprints
    eos = session.exec(
        select(EngineeringObservation).order_by(EngineeringObservation.eo_id)
    ).all()

    out = _doc_header(week, f"Engineering Observation Register — {week}")
    out += "Brain Ops is the authoritative store for Engineering Observations.\n\n"
    out += f"Total EOs: **{len(eos)}**\n\n"

    if not eos:
        out += "*No Engineering Observations recorded yet.*\n"
        return out

    # Status summary
    by_status: dict = {}
    for eo in eos:
        by_status[eo.status] = by_status.get(eo.status, 0) + 1

    out += "## Status Summary\n\n"
    out += "| Status | Count |\n|---|---|\n"
    for status, count in sorted(by_status.items()):
        out += f"| {status} | {count} |\n"
    out += "\n---\n\n"

    out += "## Engineering Observations\n\n"
    for eo in eos:
        out += f"### [[{eo.eo_id}]] — {eo.title}\n\n"
        out += f"| Field | Value |\n|---|---|\n"
        out += f"| EO ID | `{eo.eo_id}` |\n"
        out += f"| Layer | {eo.layer or '—'} |\n"
        out += f"| Sprint Opened | {eo.sprint_opened or '—'} |\n"
        out += f"| Status | **{eo.status}** |\n"
        out += f"| Confidence | {eo.confidence or '—'} |\n"
        out += f"| Evidence Count | {eo.evidence_count} |\n"
        out += f"| Linked ER | {f'[[{eo.linked_er_id}]]' if eo.linked_er_id else '—'} |\n"
        out += f"| Monitoring Expires | {_safe_iso(eo.monitoring_window_expires)} |\n\n"
        if eo.hypothesis:
            out += f"**Hypothesis:** {eo.hypothesis}\n\n"
        if eo.trigger_condition:
            out += f"**Trigger:** {eo.trigger_condition}\n\n"
        if eo.exit_criteria:
            out += f"**Exit Criteria:** {eo.exit_criteria}\n\n"
        if eo.notes:
            out += f"**Notes:** {eo.notes}\n\n"
        out += "---\n\n"

    return out


# ─────────────────────────────────────────────────────────────
# generate_er_register
# ─────────────────────────────────────────────────────────────

def generate_er_register(week: str, session: Session) -> str:
    """
    Export all Engineering Reviews from Brain Ops database.
    Immutable IDs. Full lifecycle and evidence state.
    Article 6: Review IDs are immutable.
    """
    ers = session.exec(
        select(EngineeringReview).order_by(EngineeringReview.er_id)
    ).all()

    out = _doc_header(week, f"Engineering Review Register — {week}")
    out += "Brain Ops is the authoritative store for Engineering Reviews.\n\n"
    out += f"Total ERs: **{len(ers)}**\n\n"

    if not ers:
        out += "*No Engineering Reviews recorded yet.*\n"
        return out

    # Status summary
    by_status: dict = {}
    for er in ers:
        by_status[er.status] = by_status.get(er.status, 0) + 1

    out += "## Status Summary\n\n"
    out += "| Status | Count |\n|---|---|\n"
    for status, count in sorted(by_status.items()):
        out += f"| {status} | {count} |\n"
    out += "\n---\n\n"

    out += "## Engineering Reviews\n\n"
    for er in ers:
        out += f"### [[{er.er_id}]] — {er.title}\n\n"
        out += f"| Field | Value |\n|---|---|\n"
        out += f"| ER ID | `{er.er_id}` |\n"
        out += f"| Type | {er.review_type or '—'} |\n"
        out += f"| Layer | {er.layer or '—'} |\n"
        out += f"| Sprint Opened | {er.sprint_opened or '—'} |\n"
        out += f"| Sprint Closed | {er.sprint_closed or '—'} |\n"
        out += f"| Status | **{er.status}** |\n"
        out += f"| Confidence | {er.confidence or '—'} |\n"
        out += f"| Evidence (pos/neg) | {er.evidence_count} / {er.negative_evidence_count} |\n"
        out += f"| Evidence Threshold | {er.evidence_threshold or '—'} |\n"
        out += f"| Linked Req | {er.linked_req_id or '—'} |\n"
        out += f"| Linked EO | {f'[[{er.linked_eo_id}]]' if er.linked_eo_id else '—'} |\n"
        out += f"| Cross-System | {'Yes' if er.cross_system else 'No'} |\n"
        if er.cross_system:
            out += f"| Layer Primary | {er.layer_primary or '—'} |\n"
            out += f"| Layer Secondary | {er.layer_secondary or '—'} |\n"
        out += f"| Promotion Eligible | {er.promotion_eligibility if er.promotion_eligibility is not None else '—'} |\n\n"
        if er.hypothesis:
            out += f"**Hypothesis:** {er.hypothesis}\n\n"
        if er.verified_finding:
            out += f"**Verified Finding:** {er.verified_finding}\n\n"
        if er.retirement_reason:
            out += f"**Retirement Reason:** {er.retirement_reason}\n\n"
        out += "---\n\n"

    return out


# ─────────────────────────────────────────────────────────────
# generate_engineering_summary
# ─────────────────────────────────────────────────────────────

def generate_engineering_summary(week: str, session: Session) -> str:
    """
    Executive engineering summary for the week.
    Covers verified findings, open investigations, promotion candidates,
    and pending runtime validation items.
    """
    eos = session.exec(select(EngineeringObservation)).all()
    ers = session.exec(select(EngineeringReview)).all()
    evidence = session.exec(select(EngineeringEvidence)).all()

    # Classify
    open_eos  = [eo for eo in eos if eo.status in ("open", "monitoring")]
    closed_eos = [eo for eo in eos if eo.status == "closed"]

    promoted_ers   = [er for er in ers if er.status == "promoted"]
    candidate_ers  = [er for er in ers if er.status == "candidate"]
    open_ers       = [er for er in ers if er.status in ("draft", "evidence_collecting")]
    closed_ers     = [er for er in ers if er.status == "closed"]

    pos_evidence = sum(1 for ev in evidence if ev.evidence_type == "positive")
    neg_evidence = sum(1 for ev in evidence if ev.evidence_type == "negative")

    out = _doc_header(week, f"Engineering Summary — {week}")
    out += "Brain Ops — Authoritative Engineering Evidence Warehouse\n\n"
    out += "---\n\n"

    out += "## Health Metrics\n\n"
    out += "| Metric | Value |\n|---|---|\n"
    out += f"| Total EOs | {len(eos)} |\n"
    out += f"| Open EOs | {len(open_eos)} |\n"
    out += f"| Closed EOs | {len(closed_eos)} |\n"
    out += f"| Total ERs | {len(ers)} |\n"
    out += f"| Promoted ERs | {len(promoted_ers)} |\n"
    out += f"| Candidate ERs | {len(candidate_ers)} |\n"
    out += f"| Open ERs | {len(open_ers)} |\n"
    out += f"| Closed ERs | {len(closed_ers)} |\n"
    out += f"| Positive Evidence | {pos_evidence} |\n"
    out += f"| Negative Evidence | {neg_evidence} |\n"
    if pos_evidence + neg_evidence > 0:
        neg_ratio = round(neg_evidence / (pos_evidence + neg_evidence) * 100, 1)
        out += f"| Negative Evidence Ratio | {neg_ratio}% |\n"
    out += "\n---\n\n"

    if promoted_ers:
        out += "## Promoted Engineering Reviews\n\n"
        for er in promoted_ers:
            out += f"- [[{er.er_id}]] — {er.title}"
            if er.verified_finding:
                out += f": {er.verified_finding[:100]}"
            out += "\n"
        out += "\n---\n\n"

    if candidate_ers:
        out += "## Promotion Candidates\n\n"
        out += "> Promotion decisions belong to Engineering Review (ChatGPT) — Article 9.\n\n"
        for er in candidate_ers:
            out += f"- [[{er.er_id}]] — {er.title} (confidence={er.confidence or '?'})\n"
        out += "\n---\n\n"

    if open_ers:
        out += "## Open Engineering Reviews\n\n"
        for er in open_ers:
            out += (
                f"- [[{er.er_id}]] — {er.title} "
                f"(status={er.status}, evidence={er.evidence_count}/{er.negative_evidence_count})\n"
            )
        out += "\n---\n\n"

    if open_eos:
        out += "## Active Engineering Observations\n\n"
        for eo in open_eos:
            out += f"- [[{eo.eo_id}]] — {eo.title} (evidence={eo.evidence_count})\n"
        out += "\n---\n\n"

    out += "## Pending Runtime Validation\n\n"
    out += (
        "- WAIT / FILTER_FAIL event mirroring: Pending W27 Runtime Validation\n"
        "- Cross-system Reflex timeline: Pending Source Review #5 (reflex.py)\n"
        "- Obsidian wiki link extension: Pending Source Review #4 (formatter.py)\n\n"
    )
    out += "---\n\n"
    out += f"*Engineering Summary — {week} — Generated by Brain Ops*\n"
    return out
